// The desk's build (spec S-001, Toolchain). It checks; it doesn't transform what deploys.
//
//   node tools/build.mjs          check (CI): J7, package.json, imports, and that the generated
//                                 files match their sources
//   node tools/build.mjs --write  regenerate lib/config.js and public/lib/ from their sources
//
// The deploy job runs no build and installs nothing under src/, so every file it serves is
// committed. Two kinds are generated, and the check fails when either is stale:
//   - lib/config.js, from config/projects.json (J7), which the Functions and the page import;
//   - public/lib/<file>, byte-identical copies of the page's modules in lib/, because only
//     public/ is served.
// It uses nothing but Node's standard library.

import { readFileSync, writeFileSync, readdirSync, existsSync, statSync, mkdirSync, unlinkSync } from 'node:fs';
import { join, dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { validateConfig } from '../lib/configcheck.js';

const SRC = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const WRITE = process.argv.includes('--write');

// The modules the page loads; each is copied to public/lib/ unchanged.
export const PAGE_LIB = ['config.js', 'exp001.js', 'links.js', 'markdown.js', 'model.js', 'records.js',
  'scheduler.js', 'store.js', 'timefmt.js', 'universe.js'];
const DEPENDENCY_BLOCKS = ['dependencies', 'optionalDependencies', 'peerDependencies', 'bundleDependencies',
  'bundledDependencies'];
const LIFECYCLE = ['preinstall', 'install', 'postinstall', 'preprepare', 'prepare', 'postprepare', 'prepack',
  'postpack', 'prepublish', 'prepublishOnly', 'publish', 'postpublish'];
const IMPORT_ROOTS = ['functions', 'lib', 'public'];

const errors = [];
const read = (p) => readFileSync(join(SRC, p), 'utf8');

// package.json: no runtime dependencies, no lifecycle scripts.
const pkg = JSON.parse(read('package.json'));
for (const b of DEPENDENCY_BLOCKS) if (b in pkg) errors.push(`package.json has a "${b}" block; the desk has no runtime dependencies`);
for (const s of LIFECYCLE) if (pkg.scripts && s in pkg.scripts) errors.push(`package.json has the lifecycle script "${s}"`);

// J7.
let config = null;
try {
  config = JSON.parse(read('config/projects.json'));
} catch (e) {
  errors.push(`config/projects.json is not valid JSON: ${e.message}`);
}
if (config) for (const e of validateConfig(config)) errors.push(`config/projects.json: ${e}`);

const generated = new Map();
if (config) {
  generated.set('lib/config.js', '// GENERATED by tools/build.mjs from config/projects.json (J7). Do not edit;\n'
    + '// edit config/projects.json and run `npm --prefix src run sync`.\n'
    + `export default ${JSON.stringify(config, null, 2)};\n`);
}
const libText = (f) => (generated.has(`lib/${f}`) ? generated.get(`lib/${f}`) : read(`lib/${f}`));
for (const f of PAGE_LIB) {
  if (!existsSync(join(SRC, 'lib', f)) && !generated.has(`lib/${f}`)) {
    errors.push(`lib/${f} is missing`);
    continue;
  }
  generated.set(`public/lib/${f}`, libText(f));
}

if (WRITE && errors.length === 0) {
  mkdirSync(join(SRC, 'public/lib'), { recursive: true });
  for (const [p, text] of generated) writeFileSync(join(SRC, p), text);
  for (const f of readdirSync(join(SRC, 'public/lib'))) {
    if (!PAGE_LIB.includes(f)) unlinkSync(join(SRC, 'public/lib', f));
  }
  console.log(`wrote ${generated.size} generated files`);
}

for (const [p, text] of generated) {
  const full = join(SRC, p);
  if (!existsSync(full) || readFileSync(full, 'utf8') !== text) {
    errors.push(`${p} is stale or missing; run \`npm --prefix src run sync\``);
  }
}
if (existsSync(join(SRC, 'public/lib'))) {
  for (const f of readdirSync(join(SRC, 'public/lib'))) {
    if (!PAGE_LIB.includes(f)) errors.push(`public/lib/${f} is not a page module; remove it`);
  }
}

// Imports: the Functions and the page import only from functions/, lib/ and public/.
function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) walk(full, out);
    else if (/\.(m?js)$/.test(name)) out.push(full);
  }
  return out;
}
const IMPORT_RE = /(?:^|[\s;])(?:import|export)\s[^'"]*?from\s*['"]([^'"]+)['"]|import\s*\(\s*['"]([^'"]+)['"]\s*\)|^\s*import\s*['"]([^'"]+)['"]/gm;
for (const root of ['functions', 'lib', 'public']) {
  const dir = join(SRC, root);
  if (!existsSync(dir)) continue;
  for (const file of walk(dir)) {
    const text = readFileSync(file, 'utf8');
    for (const m of text.matchAll(IMPORT_RE)) {
      const spec = m[1] || m[2] || m[3];
      const rel = relative(SRC, file);
      if (!spec.startsWith('./') && !spec.startsWith('../')) {
        errors.push(`${rel} imports "${spec}"; only relative imports inside src/ are allowed`);
        continue;
      }
      const target = relative(SRC, resolve(dirname(file), spec));
      const top = target.split(/[\\/]/)[0];
      if (target.startsWith('..') || !IMPORT_ROOTS.includes(top)) {
        errors.push(`${rel} imports ${spec}, outside functions/, lib/ and public/`);
      } else if (root === 'public' && top !== 'public') {
        errors.push(`${rel} imports ${spec}, which public/ doesn't serve`);
      } else if (!existsSync(resolve(dirname(file), spec))) {
        errors.push(`${rel} imports ${spec}, which doesn't exist`);
      }
    }
  }
}

if (errors.length) {
  for (const e of errors) console.error(`build: ${e}`);
  process.exit(1);
}
console.log(`build: PASS (${config.projects.length} connected projects; ${PAGE_LIB.length} page modules in step)`);
